### ISSUE TITLE
Good, but not perfect, please refer/suggestion

### ISSUE THREAD

**Issue by dnknn** [dvdvdmt/popup-tab-switcher#21]
Seeing that this extension is still being updated and developed, come on❣
`Popup tab switcher` has 2 shortcomings currently 👇

-  ### The popup panel cannot be set to not display.
> The Popup panel of the `Popup tab switcher` has a wealth of setting options, 
which is very good, but it should also be supported not to be displayed.

<details>
<summary>Click to 👁view screenshot</summary>

![Pic-200702_1402](https://user-images.githubusercontent.com/10995302/86322038-c7098080-bc6c-11ea-9d79-f9911c2599f9.png)
</details>

---

- ### Not working on `chrome.google.com/webstore` page, not perfect on `chrome://` page.

----
The above two problems are not problems for the following extension👇
`CLUT: Cycle Last Used Tabs`
https://chrome.google.com/webstore/detail/cobieddmkhhnbeldhncnfcgcaccmehgn
https://github.com/harshayburadkar/clut-chrome-extension.git

☝Please install and test to experience,
> Use for rapid switching to last tab (by pressing once) or to the second to last used tab(by pressing rapidly twice) and so on.

In fact, it can be said that `CLUT` is perfect except that `CLUT` cannot display the Popup panel.
It also perfectly working on `chrome.google.com/webstore` page, and perfect working on `chrome://` page.

🎀So, please ※refer to the perfection of `CLUT`, come on!

**Comment by dvdvdmt** [comment]
Thank you for your interest in improving the extension! I'm very appreciate your contribution.

> The popup panel cannot be set to not display

This option is controversial because it makes almost all functions of the extension unnecessary. You can simply use CLUT instead, and it will work even better because you'll be able to switch between 3 recent tabs. I will think about incorporation of this behaviour in the extension.

> Not working on chrome.google.com/webstore page, not perfect on chrome:// page.

That is really disappointing and I will try to solve the problem in the near future.

**Comment by dnknn** [comment]
> This option is controversial because it makes almost all functions of the extension unnecessary.

No. I mean that in `Popup tab switcher`, the function is still the same, just not showing `popup panel`
Because, after all, `popup panel` is highly customized, so sometimes want to display, and sometimes want to not display.

**Comment by dvdvdmt** [comment]
I see your point, and I think I'll add opacity option. But my current plan is to make PTS work smooth in every possible scenario, especially in those cases where its popup can't be shown (chrome:// pages, chrome web store, etc), or the page is not focused (focus on "search bar" or "find on the page bar").

**Comment by dnknn** [comment]
> But my current plan is to make PTS work smooth in every possible scenario, especially in those cases where its popup can't be shown (chrome:// pages, chrome web store, etc), or the page is not focused (focus on "search bar" or "find on the page bar").

Yes, this problem is the most **basic/kernel/critical/important**;
otherwise the function is equal to **zero** no matter how good.

> the page is not focused (focus on "search bar" or "find on the page bar").

Still referring to CLUT, it does not have this problem, and it is very smooth and stable when switching every recent tab.

**Comment by dvdvdmt** [comment]
But why do you want to use PTS instead of CLUT, especially if you don't need a visual feedback?

**Comment by dnknn** [comment]
> But why do you want to use PTS instead of CLUT, especially if you don't need a visual feedback?

Because `PTS's Popup panel` is also beautiful and highly customizable.
But `PTS's Popup panel`  can not ON/OFF(show/unshow), 
So, which means that you can not:  show it if want to show it, and unshow it if don't want to show it.
if ON/OFF, it will  is more convenient and will not be restricted.
In addition, there are not many such good extensions on the Chrome-store, hope that PTS can also be the best.
