### ISSUE TITLE
Keyboard shortcut doesnt open the popup switcher nor does tabs switch

### ISSUE THREAD

**Issue by Yash089610** [dvdvdmt/popup-tab-switcher#63]
After the recent updates, sometimes the keyboard shortcut doesnt work. So there is no way of using the switcher. I couldnt reproduce the exact reason when and why this happens but there is some issue. It works if I restart chrome.

**Comment by dvdvdmt** [comment]
Thank you for reporting this @Yash089610 👍
I think it is a strange decision of mine to restrict the tab initialization time to 100ms. I'll remove this restriction soon.

**Comment by Yash089610** [comment]
Great!

**Comment by Yash089610** [comment]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/42301695/190620489-2bec2445-2377-4ca6-a06a-ee562b8e98f6.png">

**Comment by Yash089610** [comment]
Ig some issue again

**Comment by dvdvdmt** [comment]
That is unavoidable in the current implementation, some of the tabs may not
allow the extension to show its pop-up. For example, that can be any tab in
loading state, during the page document loading the extension can't
executive its content script. I'm going to make the extension much more
reliable in the future, it will not depend on the page document but will
use a separate temporary window to show itself.

**Comment by Yash089610** [comment]
I dont mind the current implementation. But if such an error occurs, it shouldnt crash the whole switcher. Infact the switcher should be working back automatically if it crashes, if something like this is possible.

**Comment by dvdvdmt** [comment]
@Yash089610 I think I'm fixed the problem here #67 . Also the error "Could not establish connection" should not occur after the update.

**Comment by Yash089610** [comment]
I will update if I face any similar issue.
Meanwhile this error came.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/42301695/191358140-907e5b78-2db5-40a3-96a6-9a6c0e0f8c61.png">

**Comment by Yash089610** [comment]
> @Yash089610 I think I've fixed the problem here #67 . Also the error "Could not establish connection" should not occur after the update.

So now frequently the switcher crashes. But it doesnt show any error in the chrome extension page. But it doesnt run using keyboard shortcuts. Have to turn it off and on to run it. Any way to debug this? And is this issue with just me?

**Comment by Yash089610** [comment]
![image](https://user-images.githubusercontent.com/42301695/191838984-1e8680ba-df69-4c39-bb8a-58998c0ddad3.png)

Also when I click the service worker hyperlink in the extensions page, it shows this error. Tried other extensions but they dont show any error.

**Comment by dvdvdmt** [comment]
Hi @Yash089610 
The problem with empty source map file is not critical one.

I think that you faced the issue with the extension auto update that may cause it to stop working, it is a long lasting bug that is connected to Manifest V3 extensions ([details](https://bugs.chromium.org/p/chromium/issues/detail?id=1271154#c68)).
Following those steps you can help the Google Chrome team to find out the problem. Of course there is a chance that I'm wrong and the problem is really in the extension itself.

**Comment by Yash089610** [comment]
Hi @dvdvdmt 
If the bug was caused by autoupdate, I would have faced it just once, but I am facing it regularly. And no error shows up in the extensions page. The keyboard shortcuts dont respond but I can click the extension from extension list to open the recent tabs list. Even after doing this keyboard shortcuts dont showup the list. I need to turn off and on the extension to fix it.

**Comment by dvdvdmt** [comment]
I think I have this problem also, but I don't fully understand how to repeat it. Until it is fixed, could you please use the older version of extension and tell me if the is such a problem? Here is how you can do it https://github.com/dvdvdmt/popup-tab-switcher/issues/61#issuecomment-1234556774

**Comment by Yash089610** [comment]
> I think I have this problem also, but I don't fully understand how to repeat it. Until it is fixed, could you please use the older version of extension and tell me if the is such a problem? Here is how you can do it [#61 (comment)](https://github.com/dvdvdmt/popup-tab-switcher/issues/61#issuecomment-1234556774)

I am using the old version only. It works perfectly :)
